language: python

install:
    - pip install -e .

matrix:
    include:
        - os: linux
          python: 2.7
          
        - os: linux
          python: 3.6
          
script:
    - python -m pytest
